# Generated by Django 4.0.6 on 2022-08-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_approval_teal_url_verifiedcontract_approval_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifiedcontract',
            name='submitter_ip',
            field=models.CharField(default='DEFAULT', max_length=128),
        ),
    ]
