apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: "2022-08-09T18:03:30Z"
  name: {{ .Release.Name }}-purestake-api-secret
  resourceVersion: "494254"
  uid: 75347efb-f3fb-4a08-af45-c9824d99269f
type: Opaque
data:
  PURESTAKE_API_KEY: {{ .Values.purestake_api_key }}
